version: "3.8"

services:
  driverless:
    build: .
    container_name: driverless-viewer
    ports:
      - "8080:8080"
    volumes:
      # Mount output directory to persist results
      - ./output:/app/output
      # Mount data directory for custom input files
      - ./data:/app/data
    environment:
      - SERVER_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
